=== floss-fund/website/static/schema/v1.0.0/funding.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": ["version", "entity", "funding"],
    "properties": {
        "version": {
            "type": "string",
            "description": "Schema version"
        },
        "entity": {
            "type": "object",
            "description": "The entity associated with the project, soliciting funds.",
            "required": ["type", "role", "name", "email", "description", "webpageUrl"],
            "properties": {
                "type": {
                    "type": "string",
                    "description": "Type of the entity. [individual, group, organisation, other], Use the closest approximation.",
                    "enum": ["individual", "group", "organisation", "other"]
                },
                "role": {
                    "type": "string",
                    "description": "Role in relation to the entity. [owner, steward, maintainer, contributor, other]. Use the closest approximation.",
                    "enum": ["owner", "steward", "maintainer", "contributor", "other"]
                },
                "name": {
                    "type": "string",
                    "description": "Name of the entity.",
                    "maxLength": 250
                },
                "email": {
                    "type": "string",
                    "description": "Contact email.",
                    "maxLength": 250
                },
                "phone": {
                    "type": "string",
                    "description": "Contact phone number. Generally suitable for organisations.",
                    "maxLength": 32
                },
                "description": {
                    "type": "string",
                    "description": "Information about the entity.",
                    "maxLength": 2000
                },
                "webpageUrl": {
                    "type": "object",
                    "required": ["url"],
                    "properties": {
                        "url": {
                            "type": "string",
                            "description": "Webpage with information about the entity.",
                            "anyOf": [
                                { "pattern": "^(https?://)" },
                                { "pattern": "^$" }
                            ],
                            "maxLength": 250
                        },
                        "wellKnown": {
                            "type": "string",
                            "description": "Required if the above url and the URL of the funding.json manifest do not have the same hostname. This url should have the same hostname as the url to verify that the publisher of the manifest is authorised to solicit funding on behalf of the url. The url should end with /.well-known/funding-manifest-urls.",
                            "anyOf": [
                                { "pattern": "^(https?://).*/\\.well-known/funding-manifest-urls$" },
                                { "pattern": "^$" }
                            ],
                            "maxLength": 250
                        }
                    }
                }
            }
        },
        "projects": {
            "type": "array",
            "items": {
                "type": "object",
                "description": "One or more projects for which the funding is solicited.",
                "required": ["guid", "name", "description", "webpageUrl", "repositoryUrl", "licenses", "tags"],
                "properties": {
                    "guid": {
                        "type": "string",
                        "description": "A short unique ID for the project. Lowercase-alphanumeric-dashes only. eg: my-cool-project.",
                        "anyOf": [
                            { "pattern": "^[a-z0-9-]+$" },
                            { "pattern": "^$" }
                        ],
                        "maxLength": 32
                    },
                    "name": {
                        "type": "string",
                        "description": "Name of the project.",
                        "maxLength": 250
                    },
                    "description": {
                        "type": "string",
                        "description": "Description of the project.",
                        "maxLength": 2000
                    },
                    "webpageUrl": {
                        "type": "object",
                        "required": ["url"],
                        "properties": {
                            "url": {
                                "type": "string",
                                "description": "Webpage with information about the project.",
                                "pattern": "^(https?://)",
                                "maxLength": 250
                            },
                            "wellKnown": {
                                "type": "string",
                                "description": "Required if the above url and the URL of the funding.json manifest do not have the same hostname. This url should have the same hostname as the url to verify that the publisher of the manifest is authorised to solicit funding on behalf of the url. The url should end with /.well-known/funding-manifest-urls.",
                                "anyOf": [
                                    { "pattern": "^(https?://).*/\\.well-known/funding-manifest-urls$" },
                                    { "pattern": "^$" }
                                ],
                                "maxLength": 250
                            }
                        }
                    },
                    "repositoryUrl": {
                        "type": "object",
                        "required": ["url"],
                        "properties": {
                            "url": {
                                "type": "string",
                                "description": "URL of the repository where the project's source code and other assets are available.",
                                "pattern": "^(https?://)",
                                "maxLength": 250
                            },
                            "wellKnown": {
                                "type": "string",
                                "description": "Required if the above url and the URL of the funding.json manifest do not have the same hostname. This url should be a file in the repository to verify that the publisher of the manifest is authorised to solicit funding on behalf of the url. The url should end with /.well-known/funding-manifest-urls.",
                                "anyOf": [
                                    { "pattern": "^(https?://).*/\\.well-known/funding-manifest-urls$" },
                                    { "pattern": "^$" }
                                ],
                                "maxLength": 250
                            }
                        }
                    },
                    "licenses": {
                        "type": "array",
                        "description": "The project's licenses (up to 5). For standard licenses, use the license ID from the SDPX index prefixed by \"spdx:\". eg: \"spdx:GPL-3.0\", \"spdx:CC-BY-SA-4.0\".",
                        "maxItems": 5,
                        "items": {
                            "type": "string"
                        }
                    },
                    "tags": {
                        "type": "array",
                        "description": "Up to 10 general tags describing the project. For reference, see https://floss.fund/static/project-tags.txt.",
                        "maxItems": 10,
                        "items": {
                            "type": "string",
                            "pattern": "^[a-z0-9-]+$",
                            "maxLength": 32
                        }
                    }
                }
            }
        },
        "funding": {
            "type": "object",
            "description": "This describes one or more channels via which the entity can receive funds.",
            "required": ["channels", "plans"],
            "properties": {
                "channels": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": ["guid", "type"],
                        "properties": {
                            "guid": {
                                "type": "string",
                                "description": "A short unique ID for the channel. Lowercase-alphanumeric-dashes only. eg: mybank, my-paypal.",
                                "pattern": "^[a-z0-9-]+$",
                                "maxLength": 32
                            },
                            "type": {
                                "type": "string",
                                "description": "Type of the channel. [bank, payment-provider, cheque, cash, other].",
                                "enum": ["bank", "payment-provider", "cheque", "cash", "other"]
                            },
                            "address": {
                                "type": "string",
                                "description": "A short unstructured textual representation of the payment address for the channel. eg: \"Account: 12345 (branch: ABCX)\", \"mypaypal@domain.com\", \"https://payment-url.com\", or a physical address for cheques.",
                                "maxLength": 250
                            },
                            "description": {
                                "type": "string",
                                "description": "Any additional description or instructions for the payment channel.",
                                "maxLength": 500
                            }
                        }
                    }
                },
                "plans": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": ["guid", "status", "name", "amount", "currency", "frequency", "channels"],
                        "properties": {
                            "guid": {
                                "type": "string",
                                "description": "A short unique ID for the plan. Lowercase-alphanumeric-dashes only. eg: mybank, paypal.",
                                "pattern": "^[a-z0-9-]+$",
                                "maxLength": 32
                            },
                            "status": {
                                "type": "string",
                                "description": "Indicates whether this plan is currently active or inactive. [active, inactive].",
                                "enum": ["active", "inactive"]
                            },
                            "name": {
                                "type": "string",
                                "description": "Name of the funding plan. eg: \"Starter support plan\", \"Infra hosting\", \"Monthly funding plan\".",
                                "maxLength": 250
                            },
                            "description": {
                                "type": "string",
                                "description": "Any additional description or instructions for the funding plan."
                            },
                            "amount": {
                                "type": "number",
                                "description": "The solicited amount for this plan. 0 is a wildcard that indicates \"any amount\"."
                            },
                            "currency": {
                                "type": "string",
                                "description": "Three letter ISO 4217 currency code. eg: USD, EUR.",
                                "pattern": "^[A-Z]{3}$"
                            },
                            "frequency": {
                                "type": "string",
                                "description": "Frequency of the funding. [one-time, weekly, fortnightly, monthly, yearly, other]",
                                "enum": ["one-time", "weekly", "fortnightly", "monthly", "yearly", "other"]
                            },
                            "channels": {
                                "type": "array",
                                "description": "One or more channel IDs defined in channels[] via which this plan can accept payments",
                                "items": {
                                    "type": "string",
                                    "pattern": "^[a-z0-9-]+$",
                                    "maxLength": 32
                                }
                            }
                        }
                    }
                },
                "history": {
                    "type": "array",
                    "description": "A simple summary of funding history. Only include if at least one, either income or expenses, have to be communicated.",
                    "items": {
                        "type": "object",
                        "required": ["year", "currency"],
                        "properties": {
                            "year": {
                                "type": "integer",
                                "description": "Year (fiscal, preferably)."
                            },
                            "income": {
                                "type": "number",
                                "description": "Income for the year."
                            },
                            "expenses": {
                                "type": "number",
                                "description": "Expenses for the year."
                            },
                            "taxes": {
                                "type": "number",
                                "description": "Taxes for the year."
                            },
                            "currency": {
                                "type": "string",
                                "description": "Three letter ISO 4217 currency code. eg: USD, EUR.",
                                "pattern": "^[A-Z]{3}$"
                            },
                            "description": {
                                "type": "string",
                                "description": "Any additional description.",
                                "maxLength": 500
                            }
                        }
                    }
                }
            }
        }
    }
}

=== floss-fund/website/static/static/funding.example.json
{
    "version": "v1.0.0",
    "entity": {
        "type": "individual",
        "role": "maintainer",
        "name": "The One (demo)",
        "email": "neo@example.com",
        "phone": "",
        "description": "I'm a developer interested in preserving digital freedoms and the decentralised and open nature of the internet. I like breaking down barriers in the cyberspace with FOSS technologies.\n\nSometimes I can't shake the feeling that the system we're living in isn't quite what it seems. That there is no spoon.\n\nPS: This is a dummy listing.",
        "webpageUrl": {
            "url": "https://example.com",
            "wellKnown": ""
        }
    },
    "projects": [{
        "guid": "zombo-app",
        "name": "Zombo App (demo)",
        "description": "The Zombo App is a database application that solves many problems and makes anything possible. Anything at all. Its possibilities are only limited by the user's own imagination.\n\nIt has been in active development for a decade and is used by millions of people worldwide. It is the next frontier.\n\nPS: This is a dummy demo listing.",
        "webpageUrl": {
            "url": "https://example.com/projects/zombo"
        },
        "repositoryUrl": {
            "url": "https://github.com/example/zombo-app",
            "wellKnown": "https://github.com/example/zombo-app/blob/main/.well-known/funding-manifest-urls"
        },
        "licenses": ["spdx:AGPL-3.0"],
        "tags": ["database", "columnar-database", "high-performance", "key-value-store"]
    },
    {
        "guid": "vb-gooey",
        "name": "VB Gooey IP tracer (demo)",
        "description": "Using quantum-entangled packet sniffers, this cutting-edge Visual Basic GUI IP Tracer employs hyper-threaded blockchain algorithms to decrypt the target's digital DNA signature. The system's neural network of overclocked RAM crystals generates a real-time holographic map of cyberspace, pinpointing the perp's location with nanosecond precision.\n\nIn addition, its turbo-encabulated flux capacitor and multi-dimensional firewall penetrator, allows any hyper-dimensional air-gapped network to be broken into with ease.\n\n\n\nPS: This is a dummy demo listing.",
        "webpageUrl": {
            "url": "https://vb-gooey-ip-tracer.net",
            "wellKnown": "https://vb-gooey-ip-tracer.net/.well-known/funding-manifest-urls"
        },
        "repositoryUrl": {
            "url": "https://github.com/example/vb-gooey-ip-tracer",
            "wellKnown": "https://github.com/example/vb-gooey-ip-tracer/blob/main/.well-known/funding-manifest-urls"
        },
        "licenses": ["spdx:MIT"],
        "tags": ["high-performance", "security", "gui", "networking"]
    }],
    "funding": {
        "channels": [
            {
                "guid": "mybank",
                "type": "bank",
                "address": "",
                "description": "Will accept direct bank transfers. Please e-mail me for details."
            },
            {
                "guid": "mypay",
                "type": "payment-provider",
                "address": "https://example.com/payme/@myid",
                "description": "Pay with your debit/credit card through this gateway and setup recurring subscriptions."
            }
        ],
        "plans": [
            {
                "guid": "hosting-monthly",
                "status": "active",
                "name": "Hosting support",
                "description": "This will cover the monthly server hosting costs for the projects.",
                "amount": 250,
                "currency": "USD",
                "frequency": "monthly",
                "channels": ["mypay"]
            },
            {
                "guid": "developer-time",
                "status": "active",
                "name": "Developer compensation",
                "description": "This will cover the cost of one developer working part-time on the projects.",
                "amount": 1000,
                "currency": "USD",
                "frequency": "monthly",
                "channels": ["mybank"]
            },
            {
                "guid": "angel-plan",
                "status": "active",
                "name": "Goodwill plan",
                "description": "Pay anything you wish to show your goodwill for the project.",
                "amount": 0,
                "currency": "USD",
                "frequency": "one-time",
                "channels": ["mybank", "mypay"]
            }
        ],
        "history": [
            {"year": 2020, "income": 10000, "expenses": 2000, "taxes": 200, "currency": "USD", "description": "Started accepting donations for the first time."},
            {"year": 2021, "income": 15000, "expenses": 5000, "taxes": 500, "currency": "USD", "description": ""},
            {"year": 2022, "income": 30000, "expenses": 10000, "taxes": 2000, "currency": "USD", "description": ""},
            {"year": 2023, "income": 25000, "expenses": 15000, "taxes": 1500, "currency": "USD", "description": "There was a dip, but we see this improving."}
        ]
    }
}
